service: score 
app: trashpanda
org: mtuckerb

frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

functions:
  score:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /trashpanda
          method: any
